spring:
  application:
    name: LeaveDayManagement
  datasource:
    url: jdbc:mysql://mysql-15ac9fa2-hcmut-5139.c.aivencloud.com:26104/defaultdb
    username: avnadmin
    password: AVNS_alF4Nbi7tGGFzj_WkrI
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyencongthanh2406@gmail.com
    password: nsqhwjrvowpqfrge
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

jwt:
  secret-key: "AplusplusHK242SCRUM_PROJECT12345678"